//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeafSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountInformation()
        {
            this.FingerprintTemplates = new HashSet<FingerprintTemplate>();
            this.UserInformations = new HashSet<UserInformation>();
        }
    
        public int AccountID { get; set; }
        public string AccountNumber { get; set; }
        public string AccountUsername { get; set; }
        public System.DateTime AccountCreationDate { get; set; }
        public int TypeID { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FingerprintTemplate> FingerprintTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInformation> UserInformations { get; set; }
    }
}
