//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeafSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FingerprintTemplate
    {
        public int TemplateID { get; set; }
        public int AccountID { get; set; }
        public int MinutiaeTemplateID { get; set; }
    
        public virtual AccountInformation AccountInformation { get; set; }
        public virtual MinutiaeTemplatePath MinutiaeTemplatePath { get; set; }
    }
}
